[package]
name = "rstool"
version = "0.1.0"
edition = "2021"
authors = ["lopo<lopo@zju.edu.cn>"]
description = "a small tools written in rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
ipconfig = "0.3.1"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
rocket = "0.5.0-rc.2"
serde = { version = "1.0.147", features = ["derive"] }
